# Generated by Django 2.1.5 on 2019-02-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('Horodate', models.DateTimeField(primary_key=True, serialize=False)),
                ('Valeur', models.IntegerField(max_length=10)),
            ],
        ),
    ]
