# Generated by Django 2.1.5 on 2019-02-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightdash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='Valeur',
            field=models.IntegerField(default=0),
        ),
    ]
