# Generated by Django 2.1.5 on 2019-03-11 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightdash', '0002_auto_20190205_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abonnementHPHC', models.BooleanField(default=True)),
                ('tarifHP', models.FloatField(default=0.1579)),
                ('tarifHC', models.FloatField(default=0.1228)),
                ('debutHC', models.TimeField(default=datetime.time(22, 0))),
                ('finHC', models.TimeField(default=datetime.time(6, 0))),
            ],
        ),
    ]
