# Generated by Django 2.1.5 on 2019-03-11 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightdash', '0003_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='debutHC',
            field=models.TimeField(default=datetime.time(22, 0), null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='finHC',
            field=models.TimeField(default=datetime.time(6, 0), null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tarifHC',
            field=models.FloatField(default=0.1228, null=True),
        ),
    ]
