# Generated by Django 2.1.5 on 2019-03-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightdash', '0004_auto_20190311_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('base', models.IntegerField()),
                ('iinst', models.IntegerField()),
                ('papp', models.IntegerField()),
            ],
        ),
    ]
