# Generated by Django 2.1.5 on 2019-03-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightdash', '0006_settings_freqpaiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='freqPaiement',
            field=models.CharField(choices=[('m', 'Mensuelle'), ('b', 'Bimestrielle')], max_length=6),
        ),
    ]
