# Generated by Django 2.1.5 on 2019-03-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightdash', '0008_auto_20190331_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='jourPaiement',
            field=models.IntegerField(default=14),
        ),
    ]
