# Generated by Django 2.1.5 on 2019-03-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightdash', '0009_settings_jourpaiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='jourPaiement',
            field=models.IntegerField(),
        ),
    ]
