# Generated by Django 2.1.5 on 2019-04-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightdash', '0010_auto_20190331_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='debutBimestre',
            field=models.CharField(choices=[('j', 'Janvier'), ('f', 'Février')], default='j', max_length=7),
        ),
    ]
