# Generated by Django 2.1.5 on 2019-04-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightdash', '0011_settings_debutbimestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='debutBimestre',
            field=models.CharField(choices=[('j', 'Janvier'), ('f', 'Février')], max_length=7),
        ),
    ]
