# Generated by Django 2.1.5 on 2019-04-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightdash', '0012_auto_20190401_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkyData10min',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('base', models.IntegerField()),
                ('iinst', models.IntegerField()),
                ('papp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LinkyDataHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('base', models.IntegerField()),
                ('iinst', models.IntegerField()),
                ('papp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LinkyDataMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('base', models.IntegerField()),
                ('iinst', models.IntegerField()),
                ('papp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LinkyDataWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('base', models.IntegerField()),
                ('iinst', models.IntegerField()),
                ('papp', models.IntegerField()),
            ],
        ),
    ]
